INSERT INTO GENDER(value) VALUES('GENDER_MALE');
INSERT INTO GENDER(value) VALUES('GENDER_FEMALE');
INSERT INTO GENDER(value) VALUES('GENDER_OTHER');

INSERT INTO APP_LANGUAGES(name) VALUES('English');
INSERT INTO APP_LANGUAGES(name) VALUES('Hindi');
INSERT INTO APP_LANGUAGES(name) VALUES('Tamil');

